version: '3.8'

services:
  server:
    build: 
      context: .
      dockerfile: Dockerfile.dev
    depends_on:
      - db
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - db
    environment:
      DB_SCHEMA: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 4000:3000

  db:
    image: 'postgres:13'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data

  pgadmin:
    image: 'dpage/pgadmin4'
    environment:
      PGADMIN_DEFAULT_EMAIL: emp@thai.com
      PGADMIN_DEFAULT_PASSWORD: password
    depends_on:
      - db
    ports:
      - 3001:80
    volumes:
      - ./data/pgadmin:/var/lib/pgadmin
